### ISSUE TITLE
[feature request] Add a way to easily figure out what directories are unlocked.

### ISSUE THREAD

**Issue by mhogomchungu** [google/fscrypt#157] opened 2019-10-09 06:17 UTC
I am looking into adding support for fscrypt in SiriKali[1] and i have encountered a missing feature in fscrypt.

fscrypt documentation compares it to eCryptfs and cryptsetup and i will use these two as examples.

1. cryptsetup registers its unlocked volumes in ```/dev/mapper``` directory.

2. eCryptfs registers its unlocked volumes in ```/proc/self/mountinfo``` file.

As far as i can tell, fscrypt does not register its unlocked volumes anywhere and the only way to figure this out is to repeatedly call ```fscrypt status```, parse its output and then figure out how to call it again. This is tedious, error prone and to make sure no unlocked volume is missed, each and every folder in a mount point that supports encryption will have to be visited and this is very inefficient.

I think the information about unlocked volumes should come from fscrypt and should be in the following format:

```
Mount path                 Folder path         User
/mnt/foo/abcd              foo/woof            root
/mnt/abc/1234              abc/meaw            alice          
```
The first line above says user "root" unlocked a volume located at "foo/woof " in a mount point at "/mnt/foo/abcd".

The second line above says user "alice" unlocked a volume located at "abc/meaw" in a mount point at "/mnt/abc/1234".

Bonus points if it will be possible to get a list of unlocked volumes of a single user.

[1] https://github.com/mhogomchungu/sirikali/issues/122

**Comment by ebiggers** [comment] 2019-10-09 06:29
This isn't really feasible, since it's really encryption policies that are unlocked, not particular directories.  fscrypt knows which of a filesystem's encryption policies are unlocked, but it would have to scan the whole filesystem to find which directories those correspond to.

Can you elaborate on why you need this information?

Also just to clarify, there's no such thing as an "fscrypt volume", as fscrypt refers to the Linux native filesystem encryption, e.g. ext4 encryption.  The encrypted directories are simply directories on the underlying ext4 filesystem, not separate filesystems or mountpoints.

**Comment by mhogomchungu** [comment] 2019-10-09 07:32
The current behavior of SiriKali on Linux and MACOS is to ask the OS for a list of mounted volumes and then it displays the ones it cares about and it re asks the OS the list every time a volume is unlocked/locked or when it is restarted.

In a sense, SiriKali delegates the management of the list to the OS and this allows it to start and show the list or restart and still show the list and the request here is for fscrypt to manage the list so that SiriKali can ask for it when it wants it.

On Window, SiriKali keeps and show only the list of the volumes in had unlocked and this introduces a limitation that prevents SiriKali from closing while there are unlocked volumes it is managing.

I think in SiriKali UI, i will show mount point path and policy file name + protector description and if somebody want to know the path then they can put it in the description comment.

**Comment by mhogomchungu** [comment] 2019-12-05 08:13
> This isn't really feasible, since it's really encryption policies that are unlocked, not particular directories. fscrypt knows which of a filesystem's encryption policies are unlocked, but it would have to scan the whole filesystem to find which directories those correspond to.

The way fscrypt currently work to my understanding, i give it a folder path and it uses it to unlock encryption policies and then forgets about the folder path it was given and my question is, why not remember it, not for itself, but for its users.

For example, on successful unlocking, add the folder path as an entry in "/proc/self/mountinfo" and on a successful locking, remove it. This should be enough to let the kernel manage a list of unlocked directories and fscrypt will not need to scan the entire file system to get it.

**Comment by mhogomchungu** [comment] 2019-12-22 07:48
I  just released version 1.4.2 of SiriKali and this version maintains a list of unlocked directories in an internal config file.

Pros of this approach.
1. SiriKali can easily discover the list of directories it previously unlocked when it get restarted.

Cons of this approach.
2. SiriKali can not know what directories are unlocked by an external tool.

I am re opening this issue because i think its an important feature to have and because no tool will be able to have a system wide view of the list of unlocked directories without it

**Comment by josephlr** [comment] 2020-01-28 11:11
@mhogomchungu thanks for explaining why you need this feature. It's important to remember that `fscrypt`, the userspace tool, can only use the tools the Linux kernel provides it. Fundamentally, the kernel only uses "policies" and those policies are applied to directory nodes, but there is no usermode accessible mapping between policies and directories, and nothing this tool does can change that.

However, it would be possible for fscrypt to maintain the mapping itself, by storing the filesystem-relative path as part of the policy information metadata (which then gets stored in `/.fscrypt`). However, this won't actually work. Consider the following senario:

1) A user sets up fscrypt globally and on a filesystem mounted at `/mnt`. 
1) A user creates a directory at `/mnt/foo`.
1) A user encrypts the directory via `fscrypt encrypt /mnt/foo`
1) A user unlocks `/mnt/foo` and puts things in the directory, writes data, etc...
1) A user moves `/mnt/foo` to `/mnt/bar`. This doesn't actually copy anything, the directory is just renamed and the encryption policy remains the same.

The problem is that if we had `/mnt/foo`'s policy metadata contain the string `"/foo"` our information would now be stale and wrong. This could be especially bad as a new directory could be created at `/mnt/foo` that's either encrypted or unencrypted. Also, note that fscrypt supports unlocking a directory, moving it to a new location, and locking it in that new location, so using lock/unlock to maintain the mapping will also break.

Another idea would be to use [stat(2)](https://linux.die.net/man/2/stat)'s `st_ino` to solve this issue. When applying a policy to a directory, you would just add that directory's inode to the policy metadata. Then each policy would have a list of inodes it was applied to. However, you again run into the fact that Linux has no way to convert an inode to a filepath (as many filepaths can correspond to one inode).

@ebiggers is that right? Can you think of any way we could actually fix this issue?

**Comment by ebiggers** [comment] 2020-01-28 18:35
I don't know of any way.  In addition to the complications mentioned, note that even inode numbers can be reused, if the directory is deleted and then a new one created.

**Comment by josephlr** [comment] 2020-01-28 22:54
Yet another problem is that a file/sub-directory can be moved out of an encrypted directory, and it will still be encrypted. So you go from a state like:
```
foo        (unencrypted)
└── bar        (encrypted w/ Policy 1)
    ├── file1        (encrypted w/ Policy 1)
    └── file2        (encrypted w/ Policy 1)
```
to something that looks like
```
foo        (unencrypted)
├── bar        (encrypted w/ Policy 1)
│   └── file1        (encrypted w/ Policy 1)
└── file2        (encrypted w/ Policy 1)
```
and in this second state it's not even clear what "a list of unlocked directories" would even mean.

**Comment by ebiggers** [comment] 2021-12-22 03:31
Given the above discussion, I'm closing this as infeasible.

**Closed by ebiggers** 2021-12-22 03:31 UTC
Labels: enhancement
