### ISSUE TITLE
fscrypt 2.5 unlock does NOT work well with --user=$USER option

### ISSUE THREAD

**Issue by EricV2** [google/fscrypt#199] opened 2020-02-18 07:52 UTC
I have a pc backup script running rsync that runs as root. As a normal user I created a protected directory call it mysafe.

When I do as a normal user ($USER)

fscrypt unlock /home/$USER/mysafe

I open the safe almost the fisrt time (pasword is long and I may make a typo once).

When in the backup script, run as root I do:

fscrypt unlock /home/$USER/mysafe --user=$USER

I can enter the password twenty time without sucess.

It was working well before I switched to fscrypt 2.5 and 5.4 kernel. I often need to log in and open safe as $USER as the script does:

fscrypt status ${SAFE_LOCATION} | grep -q "Unlocked: Yes"

before trying to unlock...

Any hint of fix?

**Comment by ebiggers** [comment] 2020-02-19 06:33
Can you provide the output of `fscrypt status /home/$USER/mysafe`?  In particular, it would be helpful to know which type of protector and which encryption policy version you're using.  Also, in your `/etc/fscrypt.conf`, what is `use_fs_keyring_for_v1_policies` set to?

I'm also a bit confused why you would run `fscrypt unlock /home/$USER/mysafe --user=$USER` instead of just `fscrypt unlock /home/$USER/mysafe`.  For `fscrypt unlock`, the `--user` option is for who is going to access the files.  If the files will be accessed by root, and you're running the command as root, then you shouldn't give `--user`.

**Comment by EricV2** [comment] 2020-02-19 08:06
fscrypt status /home/$USER/mySafe/
"/home/$USER/mySafe/" is encrypted with fscrypt.

Policy:   1cf022692ddaef98
Options:  padding:32 contents:AES_256_XTS filenames:AES_256_CTS 
Unlocked: No

Protected with 1 protector:
PROTECTOR         LINKED  DESCRIPTION
9ea46d89ce215bd1  No      custom protector "xxxxx  Safe Lock"

 more /etc/fscrypt.conf
{
        "source": "custom_passphrase",
        "hash_costs": {
                "time": "48",
                "memory": "131072",
                "parallelism": "8"
        },
        "compatibility": "legacy",
        "options": {
                "padding": "32",
                "contents": "AES_256_XTS",
                "filenames": "AES_256_CTS"
        }
}

> I'm also a bit confused why you would run fscrypt unlock /home/$USER/mysafe --user=$USER instead of just fscrypt unlock /home/$USER/mysafe. For fscrypt unlock, the --user option is for who is going to access the files. If the files will be accessed by root, and you're running the command as root, then you shouldn't give --user.

It did that because without --user direcvtive, at the time I created the safe, it was simply not working at all, I never manager to unlock. I can try to remove it with 2.5 version. I asked debian people to provide the 2.6 version.

BTW I do not understand you comment, I just want to unlock the safe as I do when i'm logged in. but root, is not the normal user of the safe.

Once unlocked, as the script do the rsync as root, it will preserver the file ownership.

**Comment by ebiggers** [comment] 2020-02-20 03:27
Okay, I see -- since you're using a v1 encryption policy, `fscrypt` will complain if you run `fscrypt unlock` as root without the `--user` argument.  Since you're accessing the files as root, you should use `fscrypt unlock --user=root`.

However, I can't reproduce the problem where you say the passphrase isn't accepted.  It works for me.  I.e. as root, I can unlock a directory with a v1 encryption policy protected by a custom passphrase.

Is this reproducible with the latest version of `fscrypt` (v0.2.6)?  If so, can you please give clear reproduction steps?  What commands do I need to run to reproduce the problem, starting from a clean state?

As for whether the `.fscrypt` directory can be backed up and restored, yes it can.  However, note that there's currently no way to back up files in encrypted form without the key, which makes backing up `.fscrypt` mostly pointless, except in the case of a protector stored on a different filesystem.

**Comment by EricV** [comment] 2020-02-20 10:02
> Okay, I see -- since you're using a v1 encryption policy, fscrypt will complain if you run fscrypt unlock as root without the --user argument. Since you're accessing the files as root, you should use fscrypt unlock --user=root.

There is probably something I do not get : if I unlock as the normal user of the file, root can still access unencrypted files or at least I hope so or the way I backup is plain wrong. Could you confirm.

> However, I can't reproduce the problem where you say the passphrase isn't accepted. It works for me. I.e. as root, I can unlock a directory with a v1 encryption policy protected by a custom passphrase.

I created the passphrase as USER and I can unlock as user.  putting the command in a script that runs as root did not work (note that I probably started with fscrypt 2.4). I will try to use user=root and see if I can access the file correctly (but a bit later as I'm at work ATM).

> Is this reproducible with the latest version of fscrypt (v0.2.6)? If so, can you please give clear reproduction steps? What commands do I need to run to reproduce the problem, starting from a clean state?

I'm not familiar with Go language and build environment. Never used. So I cannot recompile it myself. I must wait until debian produce a 2.6 package for unstable... 

> As for whether the .fscrypt directory can be backed up and restored, yes it can. However, note that there's currently no way to back up files in encrypted form without the key, which makes backing up .fscrypt mostly pointless, except in the case of a protector stored on a different filesystem.

This sentence is probably what worries me the most because I fear I did not get the way it works and especially where are the AES key stored! and how to sire and restore it. Is it stored in the FS metadata on disk? If yes it is forever gone in case of a disk crash and I do see the URGENT need for the backup and recovery commands.

The script is supposed to backup and entire PC (only keeping the important information to recreate from scratch : I do not backup /usr/bin only the list of installed packages for exemple).

Recently I decider to use fscrypt to protect some sensible data stored in my home but wanted to backup them also ciphered on a backup disk. So I have another safe on the backup disk (another physical disk) that I also unlock before doing the transfer via rsync. The question is rather what is the procedure for restoring the safe from backup version. I can access the file unciphered on the backup, so I just need to know how to recreate the safe.

I have separate /etc filesystem  (and anyway backup) so the /etc/fscrypt.conf can be restored, then I probably only need to do the recreation of /home/$USER/mysafe before trying to restore the full /home filesystem. But then restoring the complete /home with probably replace the new .fscrypt content by backuped one which may not work. Not backuping /home/.fscrypt probably provide some extra security in case of accidental deletion/corruption.

I think the way to backup/restore correctly a ciphered directory should be better explained and if it differs between V1 or V2 policy this should be emphasized in the documentation. FS keyring vs User keyring says nothing about the strorage of the keys  and people familiar with ext4 e4crypt will be clearly confused (like me).      

Thanks for your time and patience.

**Comment by Maryse47** [comment] 2020-02-20 10:45
> There is probably something I do not get : if I unlock as the normal user of the file, root can still access unencrypted files or at least I hope so or the way I backup is plain wrong. Could you confirm.

In theory root and every other user can read decrypted files if file permissions allow them to do so. The problem with v1 policy is that it bases on user keyrings which are very fragile and if they aren't linked properly then some processes may not be able to access decrypted files even if thy have appropriate permissions. I would recommend to wait until you can use v2 policy before you start using fscrypt for a daily manner.

**Comment by EricV** [comment] 2020-02-20 12:51
> The problem with v1 policy is that it bases on user keyrings which are very fragile and if they aren't linked properly then some processes may not be able to access decrypted files even if thy have appropriate permissions. I would recommend to wait until you can use v2 policy before you start using fscrypt for a daily manner.

Well, well nice to know the software is/was not ready for everyday use when I started using it. Could have been marked as such in blinking red :-(

Then I took time read the design document, and in this document I see three possible keyring usage (in fact 4 but one is rejected : Namely Session Keyring).

The three remaining are : 
     1) User Keyring,
     2) Fscrypt keyring,
     3) Filesystem keys,

But nowhere is said where it relates to (I suppose kernel fscrypt)  policy version, or the fscrypt program version itself. I would like to know what default key management and policy is used for fscrypt:
   1) 2.4 (probably the version I started with but with a  4.19.xxx kernel),
   2) 2.5 : the Version I now have with a 5.4.x kernel (What I have)
   3) 2.6 : your current version not yet available on debian

I also would like to know what I need to start using what you call v2 policy...
Then I can unlock all the safe, copy the content to non protected dir, delete everything realted to previous fscrypt (/etc/fscrypt.conf, /fs/.fscrypt, protected dir, what else?) and restart from scratch.

Then and related to my question on how to backup and restore, reading the spec I understand that the real key used for is derived from the content of the /fs/.fscrypt content and my passphrase. But then enters the policy key and I do not understand the key flaw to get up to the policy key or the storage of policy key.

Again thanks for helping and sorry to trying to understand but my data are important to me.

**Comment by ebiggers** [comment] 2020-02-20 17:28
Regarding `fscrypt unlock` not working: I'm afraid that if you can't provide clear reproduction steps with the latest version of the `fscrypt` tool, it won't be possible to help you.

Regarding backup and restore: Although locked encrypted files can't be backed up, unlocked encrypted files can be backed up just like any other file.  And that's exactly what you're doing.  So what is the issue here?  You don't need to back up the fscrypt metadata, because you're backing up the original files.  Of course, when restoring, you have the option to use `fscrypt encrypt` to create a new encrypted directory and restore the files into it; but that has nothing to do with the backup itself.

Regarding v1 vs v2 policies: the README file covers how to enable v2 policies and how to migrate from v1 => v2.  This requires v0.2.6 or later of the `fscrypt` tool, and kernel v5.4 or later.  We haven't yet gone back and updated the original design document for the `fscrypt` tool--- but it's intended that users don't have to read that just to use `fscrypt` anyway; it's more for people who really want the full technical details.  From the user's perspective the two policy versions are very similar, except that with v2 unlocking/locking works in a more logical way.

**Comment by ebiggers** [comment] 2020-02-20 17:46
One idea though:

> fscrypt unlock /home/$USER/mysafe --user=$USER
> 
> I can enter the password twenty time without sucess.

Do you mean that the command is succeeding, but the backup process doesn't actually get access to the encrypted files?  Or do you mean that the command is failing with an error like "Incorrect Passphrase"?  If it's succeeding, then it's a keyrings problem, which can be solved by upgrading to a v2 encryption policy; or alternatively (if you're unable to upgrade `fscrypt` for some reason) you can use `--user=root`.

**Comment by EricV** [comment] 2020-02-20 18:45
> Regarding fscrypt unlock not working: I'm afraid that if you can't provide clear reproduction steps with the latest version of the fscrypt tool, it won't be possible to help you.

Fair enough. I will try when debian package the 2.6 version.

> You don't need to back up the fscrypt metadata, because you're backing up the original files.

Well, yes and no. I understand they are not really useful for the restore procedure but can serve in case of accidental deletion without real disk or fs crash.  In addition backing up a entire filesystem is much simpler with rsync especially when the things to remove are on the root of the filesystem. But then I should be careful when restoring to not overwrite with previous version doing a full rsync of the home once the safe would have been recreated and unlocked which was the way I intended to restore after recreating the safe.

>  Or do you mean that the command is failing with an error like "Incorrect Passphrase"? 

Yes the command is failing with incorrect passphrase message even trying 20 times carefully typing or typing it in a different windows to be sure it is ok and pasting it with the mouse. As if it was not getting the input correctly, or the verification of the validity of the input incorrectly failed when executed in the context of my simple shell script.

When calling the command from command line fscrypt unlock /home$USER/myshare or using the same command in a simple shell script work when run as USER.

I tried the  fscrypt unlock /home/$USER/myshare --user=root as you suggested from command line and it worked also. I can tried to replace fscrypt unlock /home$USER/myshare --user=$USER by  fscrypt unlock /home$USER/myshare --user=root in the backup script as suggested to see if it changes anything.

The backup script contains two fscrypt unlock executed sequentially with the same passphrase but on two different directory on two different disks that have been created at different time. The first one is working correctly but with --user=root (backup destination), and the second one, source is failing even with correct input _very frequently_ (that means that sometime it works but I cannot find a pattern and no it is not because I mistype the passphrase 20 times in a raw especially when copy pasting the passphrase).

I have the same behavior on two different Linux systems (same kernel, same debian version, same fscrypt utility) but with the same unlock/backup procedure except user names and mount point.

Picture is much clearer now. Bug remains but at least with your help I progressed on the design and internals.

Thanks for your time. I can probably give you the script if really needed only obfuscating real user names and exact source/destination location but not sure it will help.

**Comment by EricV** [comment] 2020-03-04 22:56
As the debian maintainer compiled the 2.6 package, I tested it and simplified it.

#!/bin/bash

fscrypt unlock /home/xxxx/mySafe
Result=$?
exit $Result

Sometime it works, but sometime I can enter the password ten times and it fails even if the passphrase is correct. No clear pattern for systematic failure yet and when unlocked i need to reboot so takes time.

Unchanged policy and config ATM.

**Comment by ebiggers** [comment] 2020-03-04 23:07
Running `fscrypt unlock` from a script works fine for me.  Can you please give full instructions to reproduce this issue from scratch using a new installation of `fscrypt`?

Also, are you sure you're not doing something that's resulting in the wrong password being provided to `fscrypt`, like caps lock, wrong keyboard layout, something else grabbing keyboard input, etc...

**Comment by EricV** [comment] 2020-03-05 07:37
> Running fscrypt unlock from a script works fine for me. Can you please give full instructions to reproduce this issue from scratch using a new installation of fscrypt?

I think you already have the full instruction : I gave you the script, the /etc/fscrypt.conf, I have a setup that works "sometimes". So the setup is not fully broken and was working very well with fsync 2.4 and 4.19 kernel. Now I have an unmodified fscrypt setup (compared to what was working), just upgraded first to 2.5 and now 2.6 and a 5.4.x (x=23 currently) Linux kernel.

I'm ready to restart from scratch the installation but what shall I do? 

1) Unlock my safe copy it somewhere else,
2) remove the directory containing the protected file?
3) remove the .fscrypt at the top of the filesystem that contains the protected directory?
4) redo the full setup?
Could you confirm


> Also, are you sure you're not doing something that's resulting in the wrong password being provided to fscrypt, like caps lock, wrong keyboard layout, something else grabbing keyboard input, etc...

I'm not stupid: i already told you that I type the password in another window and that even copying it with a cut and paste give me the "Incorrect passphrase" and that once it goes wrong I have it in a loop. It would have detected anything related to keyboard input (Caps lock, wrong keyboard, ...). In addition when it just refuse to work, typing ^C and restarting usually works.

It is so basic  that I suspect a bug in debian, via the go compiler, libraries, or something like that. If it was not an exotic language, I would have long debugged it but I never learned anything in Go. Is there a way to echo the password I just get? 

But if the bug is in debian, it will be in Ubuntu soon and will potentially affect many users beside me. I already opened the bug in debian but so far no fix and anyway as 2.6 was not yet there, they first updated to 2.6...

**Comment by EricV** [comment] 2020-03-05 07:46
Here is my environment in debian (look at build using ). Tell me if anything looks suspicious...

dpkg -s fscrypt
Package: fscrypt
Status: install ok installed
Priority: optional
Section: admin
Installed-Size: 6626
Maintainer: Debian Go Packaging Team <team+pkg-go@tracker.debian.org>
Architecture: amd64
Version: 0.2.6-1
Depends: libc6 (>= 2.14), libpam0g (>= 0.99.7.1)
Suggests: libpam-fscrypt
Description: Tool for managing Linux filesystem encryption
 fscrypt is a high-level tool for the management of Linux filesystem
 encryption. This tool manages metadata, key generation, key wrapping,
 PAM integration, and provides a uniform interface for creating and
 modifying encrypted directories.
 .
 To use fscrypt, you must have a filesystem with encryption enabled and
 a kernel that supports reading/writing from that filesystem. Currently,
 ext4, F2FS, and UBIFS support Linux filesystem encryption. Ext4 has
 supported Linux filesystem encryption since v4.1, F2FS added support
 in v4.2, and UBIFS added support in v4.10. Other filesystems may add
 support for native encryption in the future.
Built-Using: go-md2man (= 1.0.10+ds-1), golang-1.13 (= 1.13.8-1), golang-blackfriday (= 1.5.2+git20190616.a925a15-1), golang-github-pkg-errors (= 0.9.1-1), golang-github-urfave-cli (= 1.22.2-4), golang-go.crypto (= 1:0.0~git20200221.2aa609c-1), golang-golang-x-sys (= 0.0~git20200219.cb0a6d8-1), golang-goprotobuf (= 1.3.4-2)
Homepage: https://github.com/google/fscrypt

**Comment by EricV** [comment] 2020-03-23 23:32
This are getting even worse : I can no more unlock my Safe ... Grrr

**Comment by andreas5232** [comment] 2020-04-22 08:17
I'm not sure, if this is related, but since yesterday my fscrypted home directory can't be unlocked at the first n tries. So, when I try to login via lightdm, I just see a black screen for a while and then get thrown back to the login screen. After that I loggedin as root on TTY2 and tried to unlock my users home directory manually using `--user=andreas`, but had no luck for the first 5-10 tries. Then suddenly the unlock mechanism works. Same issue persists even after reboot.
I double-checked everything very well and am quite sure, that I don't do that much password typos.

Before that I was able to login via GUI/lightdm at the first try.

```
Arch Linux (Manjaro with Cinnamon and linux-ck-kernel)
Kernel: 5.5.18-1-ck-skylake #1 SMP PREEMPT Fri, 17 Apr 2020 19:23:45 +0000 x86_64 GNU/Linux
fscrypt 0.2.7-1 (from community repo)
```

**Comment by EricV** [comment] 2020-04-24 10:43
In my case after using strace to make sure I was typing the right characters, I discovered I made two typos in the passphrase, one voluntarily and the other not. After typing at full sped several time (> 20) when it suddently unlock I looked at the traces to see why I did type...

In the mean time (initial setup and problem discovery)  I changed the keyboard and maybe the touch pattern why slightly changed so that a missing character in a word was send, when not with old keyboard.

So as usual the error was between the keyboard and the chair, but the keyboard was more involved than it should after replacement.

**Comment by ebiggers** [comment] 2020-06-09 19:25
Closing this issue since this was apparently user error, as per the [comment above](https://github.com/google/fscrypt/issues/199#issuecomment-618938662).

If anyone is still encountering problems, please open a new issue with concise, clear reproduction steps.

**Closed by ebiggers** 2020-06-09 19:25 UTC
Labels: needs reporter feedback

**Comment by cpitclaudel** [comment] 2021-05-13 07:01
I had a similar issue on a fresh Ubuntu 21.04.  I was following the instructions at https://tlbdk.github.io/ubuntu/2018/10/22/fscrypt.html .  I encrypted a test folder, which prompted me to create a new login protector.  When I then logged in as root and try to encrypt a directory using that same protector, it repeatedly complained that I was using the wrong passphrase.

In my case what worked was deleting the protector and recreating it: `fscrypt status /` to get the id of the protector, then `fscrypt metadata destroy --protector=/:<id-from-previous-step>`.

**Comment by EricV2** [comment] 2021-05-13 09:50
On 13/05/2021 09:01, Clément Pit-Claudel wrote:
>
> I had a similar issue on a fresh Ubuntu 21.04. I was following the 
> instructions at https://tlbdk.github.io/ubuntu/2018/10/22/fscrypt.html 
> . I encrypted a test folder, which prompted me to create a new login 
> protector. When I then logged in as root and try to encrypt a 
> directory using that same protector, it repeatedly complained that I 
> was using the wrong passphrase.
>
> In my case what worked was deleting the protector and recreating it: 
> |fscrypt status /| to get the id of the protector, then |fscrypt 
> metadata destroy --protector=/:<id-from-previous-step>|.
>
Thanks for the hint. Now that I know which typos I usually make, I know 
that after a few trial I will get the "right" typos. Makes it even 
harder to guess with dictionnary.

--eric
