### ISSUE TITLE
Document rescue scenario with pam passpharase

### ISSUE THREAD

**Issue by RomanValov** [google/fscrypt#115] opened 2018-12-13 15:39 UTC
Say I have fscrypt setup for my home directory using pam passphrase and got my system broken or unusable or even would like to migrate my hard drive into another system. It's unclear what steps do I have to do to recover my encrypted data i.e. running from livecd environment without associated user account available.

**Comment by EelcoA** [comment] 2019-07-06 17:22
This is my current situation. I encrypted my home dir (located on a separate partition) and had to do a reinstall of Ubuntu 18.04. And now it is unclear to me what to do. Also see https://askubuntu.com/questions/1156353/failes-to-decrypt-encrypted-home-directory-after-reinstall-of-ubuntu-18-04-fscr for my issue.

**Comment by Redsandro** [comment] 2019-11-12 18:38
I wonder about this too. I have an external drive with `fscrypt` encrypted files using `pam_passphrase`. The computer was refurbished and the user no longer exists.

There are backups on AWS Glacier but it will take effort. Given that the old user was myself and I know the user password, can I access the files on the external drive? Or are the files lost because there was crucial metadata on the root filesystem?

@ebiggers could you comment on this?

---

This might be related to https://github.com/google/fscrypt/issues/125 but I ~~don't think~~ am not sure `fscrypt` will have the same hurdles as `ecryptfs`.

**Comment by ebiggers** [comment] 2019-11-12 18:59
Login protectors are stored in the `/.fscrypt` directory on the root filesystem.  If that directory has been lost, then it's impossible to decrypt any directories that were protected by the login passphrase only (i.e., not also by a custom passphrase or raw key).

**Comment by Redsandro** [comment] 2019-11-14 17:23
Thanks for clarifying @ebiggers 

> Login protectors are stored in the `/.fscrypt` directory on the __root filesystem.__

I'm hypothesizing that this is more of a problem than it is a necessity. I'm opening a new issue at #164.

So imagine we backup `/.fscrypt/`. How would we access the files on an external fscrypted drive, attached to say a completely new linux laptop?

**Comment by ebiggers** [comment] 2019-11-14 18:48
> I'm hypothesizing that this is more of a problem than it is a necessity. I'm opening a new issue at #164.

I'm afraid it's working as intended; see https://github.com/google/fscrypt/issues/164#issuecomment-554024149.  We definitely should improve the documentation though, and maybe make `fscrypt encrypt` suggest also creating a custom passphrase protector for recovery purposes.

> So imagine we backup /.fscrypt/. How would we access the files on an external fscrypted drive, attached to say a completely new linux laptop?

It should work if you just copy the files in `/.fscrypt/protectors/` to the new computer.

**Comment by zabbal** [comment] 2019-11-14 18:55
Perhaps adding an option to specify location of protectors file explicitly would make it easier to discover? Smth like "fscrypt --protectors /media/user/backup-2/protectors" with corresponding notes in "fscrypt --help" and man page.

**Comment by Redsandro** [comment] 2019-11-15 03:26
> maybe make fscrypt encrypt suggest also creating a custom passphrase protector for recovery purposes.

Good idea. I responded to your #164 comments first; they are in a similar fashion, perhaps a bit more drastic. But I _just_ suffered the consequences of making assumptions, so I have a very clear idea of what I wish had happened when I went through the process of setting this up.

> It should work if you just copy the files in `/.fscrypt/protectors/` to the new computer.

Is the expected mountpoint of the external drive also in there? Does it need to be the same? Or is that configured using `fscrypt setup`?

E.g.:

1. `fscrypt setup /`
1. `fscrypt setup /mnt/external-drive/`
1. Copy backed up `.fscrypt/protectors/` to `/`

**Comment by ebiggers** [comment] 2019-11-15 07:16
All `fscrypt setup MOUNTPOINT` does is create `MOUNTPOINT/.fscrypt/` and two subdirectories.  So no, you don't need to run it on the external volume again.  Also, with the latest version of fscrypt you don't even have to run `fscrypt setup /`, as `fscrypt setup` (with no arguments) will do it if not already done.

Anyway, a correction: it's not quite sufficient to restore your login protector in `/.fscrypt/protectors/`. You also have to find the corresponding `.link` file in `MOUNTPOINT/.fscrypt/protectors/` on the external volume and fix the UUID to be for the new root filesystem.  E.g., if `findmnt / -o UUID` now shows `37cca723-c07b-4d70-830e-296eaee014a0`, the `.link` file should contain `UUID=37cca723-c07b-4d70-830e-296eaee014a0`.

We probably should make the protector links contain a path as a backup method to the UUID, so they keep working if the filesystem is reformatted (unless the mountpoint is also changed).  Or as a fallback, we could just search all filesystems to try to find the protector...

**Comment by Redsandro** [comment] 2019-11-15 14:27
Thanks for explaining. I will try this out this week or next week. I have a device that needs upgrading. I will do a clean install, backup the root fscrypt files, and partclone the external drive. 

> You also have to find the corresponding `.link` file in `MOUNTPOINT/.fscrypt/protectors/` on the external volume and fix the UUID to be for the new root filesystem. 

Gotcha. That's probably the UUID of `/dev/dm-0` or `/dev/mapper/vg-something` in the case of LVM.

> We probably should make the protector links contain a path as a backup method to the UUID, so they keep working if the filesystem is reformatted (unless the mountpoint is also changed). Or as a fallback, we could just search all filesystems to try to find the protector...

Sounds good. One in-between solution to help out a bit could be to add a comment to those .link files similar to fstab:

> was on /dev/sdf2 during installation.

**Comment by Redsandro** [comment] 2019-11-16 05:01
@ebiggers somehow it doesn't work. My files (and filenames) are unreadable.

Can you think of another step that I have missed?
Does the external volume need to be mounted at the exact same location as it was before?

When trying to encrypt a new directory on the system where I just restored the protector (to see if it taught me anything), I see the following errors:

```
# fscrypt encrypt --user=redsandro test
Should we create a new protector? [y/N] # y
The available protectors are: 
1 - login protector for redsandro (linked protector on "/")
NOTE: %d of the %d protectors failed to load. You may need to mount a linked filesystem. Run with --verbose for more
information.Enter the number of protector to use: 
```

Unrelated: The note is missing two digits and a newline.

**Comment by Redsandro** [comment] 2019-11-17 00:43
> You also have to find the corresponding `.link` file in `MOUNTPOINT/.fscrypt/protectors/` on the external volume and fix the UUID to be for the new root filesystem.

I figured out one problem. Unix tools are pretty adamant in adding a final newline. Both `nano` and `vim` do this.

![image](https://user-images.githubusercontent.com/1702193/69001140-22ebe880-08da-11ea-82a0-0b8440375053.png)

I did not know this was not allowed, but I noticed this using `fscrypt status`:

```
ext4 filesystem "/mnt/loop" has 2 protectors and 1 policy

PROTECTOR  LINKED  DESCRIPTION
                   [filesystem /mnt/loop: no device with UUID "1c0b38bf-test-demo-fake-7e48d4452559\n": cannot follow filesystem link]
                   [filesystem /mnt/loop: unexpected EOF: system error: on-disk metadata is corrupt]
```
(I mounted a partclone image as a loop device, which might be causeing the additional error.)

Notice the newline in the UUID.

If this is meant to be editable by humans, it would help to trim the value from the `.link` file.

**Comment by LM-HZG** [comment] 2020-07-23 10:57
> All `fscrypt setup MOUNTPOINT` does is create `MOUNTPOINT/.fscrypt/` and two subdirectories. So no, you don't need to run it on the external volume again. Also, with the latest version of fscrypt you don't even have to run `fscrypt setup /`, as `fscrypt setup` (with no arguments) will do it if not already done.
> 
> Anyway, a correction: it's not quite sufficient to restore your login protector in `/.fscrypt/protectors/`. You also have to find the corresponding `.link` file in `MOUNTPOINT/.fscrypt/protectors/` on the external volume and fix the UUID to be for the new root filesystem. E.g., if `findmnt / -o UUID` now shows `37cca723-c07b-4d70-830e-296eaee014a0`, the `.link` file should contain `UUID=37cca723-c07b-4d70-830e-296eaee014a0`.
> 
> We probably should make the protector links contain a path as a backup method to the UUID, so they keep working if the filesystem is reformatted (unless the mountpoint is also changed). Or as a fallback, we could just search all filesystems to try to find the protector...

Hello,

is this still the case? I am considering to move an encrypted folder to another disk, but cannot find an aforementioned ".link" file in my /.fscrypt/protectors/ directory. Only one binary file without specific file extension. No hint on any UUID whatsoever. 

An advice would be highly appreciated! 
Thanks!

sorry in advance for this offtopic question:
I assume it is a direct consequence of a fscrypt encrypted directory that I am only able to copy **not move** a file in and out of the dir, right? Was curious, because my nautilus refuses to do exactly that.

**Comment by ebiggers** [comment] 2020-07-23 16:33
You can't "move an encrypted directory to another disk".  You can only create a new encrypted directory on the new filesystem, then copy the files into the new directory, then (if desired) delete the original directory.

Is that what you're trying to do?

**Comment by Redsandro** [comment] 2020-07-23 21:35
You can't _"move an encrypted directory to another disk"_? Not even if you keep all metadata directories? I did not know that. I was contemplating the same thing when moving to a bigger drive.

I need to stop thinking of this as something similar to ecryptfs storage-wise.

**Comment by ebiggers** [comment] 2020-07-24 04:35
To clarify, you *can* use `mv` to "move" encrypted files to another filesystem.  (As with any other file, `mv` actually implements this as a copy+delete.)  But the source directory must be unlocked, and there is nothing special about the destination --- if you want the destination files to be encrypted, you must first create an encrypted directory at the destination.  I.e. `mv` doesn't preserve encryption by itself.

**Comment by LM-HZG** [comment] 2020-07-24 07:58
Hey guys,

thanks for replying. Probably my interpretation of what fscrypt does is also too much influenced by ecryptfs that I used for years. 

@ebiggers 
Interesting - I could swear I had troubles with mv operations in or out of an fscrypt encrypted directory last summer. Basically, it (i.e. nautilus on a ubuntu 18.04. machine) refused to finish mv with the delete operation but threw an error instead, and I had to manually delete the files afterwards. That inconvenience made me move some folders out of the encrypted path that received new files by mv's frequently.
I just made a test for the first time since then, and it behaves as you describe - like a normal mv. No nautilus complaint, nothing. Good news!

**Comment by LM-HZG** [comment] 2020-07-24 08:26
However, my initial concern was something else. Sorry if I haven't been clear about it.

I wondered, if I could recover a backup of an encrypted folder on a different system, or a drive with another UUID. Backups that I do for example with clonezilla, a tarball or whatever.

Consider this scenario:
- I have my whole home folder encrypted by fscrypt or only one particular directory in it.
- I want to make a backup of $Home because I intend to do a dist-upgrade, or want to move $Home to another partition and want to prevent worst-case scenarios.
- I'd startup my system with any live system out there, mount the partition including $Home and do a partclone or a tarball of all files included and store it somewhere safe 
- I include the /.fscrypt folder of the partition where the directory ($Home or some other)  was initially set up with fscrypt
- because my drive crashes, the update fails or any other bad forces me to recover my files from my backup

Will I be able to get all files back from the backup? Let's say on a replacement drive?

Or is a backup of files only possible in an decrypted state. What backup strategy would you propose for an encrypted $Home 
if this would be the case? 
Thanks in advance for your feedback and time!

**Comment by Redsandro** [comment] 2020-07-24 14:39
@LM-HZG @ebiggers interesting case. What happens with my encrypted home when my drive breaks and I have to restore one of my monthly `FSArchiver` (or CloneZilla) partition backups to a new drive?

I would assume it works without problems because it's just data, but that would also assume you _can_ move (i.e. copy) encrypted files in their encrypted form when the directory is _not_ unlocked.

Still not entirely clear to me what you can't do and why not.

**Comment by ebiggers** [comment] 2020-07-24 16:27
You can't do file-level backups of locked encrypted files.  (Try opening a locked encrypted file -- you'll get an error.)

You need to unlock them first, *or* do a partition-level backup.

**Comment by Redsandro** [comment] 2020-07-24 17:27
@ebiggers you are right. I can see all the (encrypted) filenames, but I can't actually see the (encrypted) contents.

So the question is if [FSArchiver](https://www.fsarchiver.org/) (and consequently tools like CloneZilla and SystemRescueCd) supports encrypted data on `ext4`. I can't really find a specific statement on that, except for this on the FAQ:

> FSArchiver is able to save/restore all Linux file-systems (ext2, ext3, ext4, reiserfs, reiser4, xfs, jfs, btrfs) as well as FAT16/FAT32 for backing up an EFS (EFI file system). **The specific file-system attributes are supported for all these file-systems.** It means that both the data (file contents, file attributes) and file-system attributes (label, uuid, block size) are preserved as well as several advanced file-system attributes such as inode-size on ext4. Anyway, **several advanced file-systems attributes still need to be implemented**, such as the journal attributes for ext4.

Assuming ext4 encryption is just a flag and nothing advanced (the tech is in the kernel), I'm guessing it will work fine. Someone should probably test this and restore a backup. :sweat_smile:

**Comment by ebiggers** [comment] 2020-07-24 17:54
Again, for file-level backups you have to unlock the files first, and then just back them up as any other files.  It won't preserve the encrypted-ness.

Partition-level backups, specifically meaning backups of the *block device* (not a file-level backup of the filesystem), will exactly preserve the entire filesystem, including encrypted files.

**Comment by Redsandro** [comment] 2020-07-24 18:34
I understand what you were saying, but without understanding the technology, I can't logically comprehend whether or not a popular tool that warns _"several advanced file-systems attributes still need to be implemented"_ can backup a _partition_ that uses a rather modern file-system attribute like native encryption.

To be clear, we're not talking about classic block-level tools like `partclone` or `dd` here. `FSArchiver` is created specifically to drop as much data as possible from the block device in order to create the smallest backup archive, and attempts to recreate a representation of the partition and file-system on restore.

**Comment by Maryse47** [comment] 2020-07-24 21:12
From the www.fsarchiver.org:
> FSArchiver is working at the file level

which mean the answer is no: you can't use it to backup encrypted ext4 files.

**Comment by Redsandro** [comment] 2020-07-26 18:55
Ok, so we need to use `partclone.ext4` to back up a partition using `fscrypt`.

The good news: **I was wrong;** Clonezilla does not use `FSArchiver` internally. It uses the `partclone` tools. It also discards unused blocks (even if they contain old data), but I tested it out, and I could successfully restore a backup made with Clonezilla.

**Comment by LM-HZG** [comment] 2020-07-27 08:06
@ebiggers Thank you for this clarification. The file level / partition level contrast is a good help to understand and remember for the future. 
Only one last thing to make it perfectly clear for me. To restore files from a partition level backup you need to have the .fscrypt encryption metadata either included in the backup of the partition, or backed up separately from the system root partition (e.g. encrypted home, that was originally on a different partition than the system) depending on were it was initially created (i.e. fscrypt setup'ed), right?

@Redsandro Good the hear you were able to restore a clonezilla backup. That makes me more confident to go down this path as well. Thanks for the confirmation.

**Comment by ebiggers** [comment] 2020-07-27 15:33
> Only one last thing to make it perfectly clear for me. To restore files from a partition level backup you need to have the .fscrypt encryption metadata either included in the backup of the partition, or backed up separately from the system root partition (e.g. encrypted home, that was originally on a different partition than the system) depending on were it was initially created (i.e. fscrypt setup'ed), right?

It depends on which type of protector the encrypted files are using.  You always need the `.fscrypt` directory on the same filesystem as the encrypted files; that will be included in the partition level backup.  But for login protectors (not custom passphrase or raw key protectors), you **also** need  `/.fscrypt` from the root filesystem.

**Comment by Redsandro** [comment] 2020-07-27 16:55
@LM-HZG commented:
> @Redsandro Good the hear you were able to restore a clonezilla backup. That makes me more confident to go down this path as well. Thanks for the confirmation.

Be careful though, occasionally there was a discussion on some Clonezilla forum about if they should switch to FSArchiver. They haven't done so and (now) I hope they never do. I used `clonezilla-live-20190903-eoan-amd64` for this. I like to stick to a version for paranoia reasons, and that's the first version that supports ZFS 0.8.

**Comment by robszy** [comment] 2021-09-11 18:08
It is shocking that there is nothing about recovery in README

**Comment by ebiggers** [comment] 2021-09-11 19:25
@robsyz: the scenario this issue was originally about (login protector on non-root filesystem) was already addressed by having `fscrypt` ask you if you want to generate a recovery passphrase in that case.  (There are several tangential discussions above, but that was the original issue.)

I'll add something to the documentation about it, but the aim was for it to "just work" and not require reading the documentation.

**Comment by robszy** [comment] 2021-09-11 19:38
Yes but user should be warned in doc about what should be done to prevent things like loss of data in #164.

For now there is 0 warning what might happen if user do nothing and says it "just work" to the day when root partition will be dead because recovery key will be drowned with all encrypted data so in docs should be paragraph about how to not lose data because of design that is different to other crypt software where only passphrase is needed to unlock data (no other usb sticks, partition etc. ).

**Comment by ebiggers** [comment] 2021-09-11 21:11
I'm sorry that there isn't better documentation, and I will be fixing this.  However, remember that for any software package, most users don't read the documentation, or only read a small part of it.  Thus, software needs to be easy to use.  This is why `fscrypt` automatically detects the case in question and asks "Protector is on a different filesystem! Generate a recovery passphrase (recommended)?" I take it that you answered "no" to that prompt?  Is there a way we could make the prompt clearer?

**Closed** 2021-09-14 03:16 UTC
Labels: documentation

**Comment by ebiggers** [comment] 2021-09-14 03:25
@robszy please check whether the new documentation at https://github.com/google/fscrypt#backup-restore-and-recovery answers your question(s).  Also please let us know if/why the prompt to automatically generate a recovery passphrase didn't address your concern(s) before you came here -- thanks!

**Comment by robszy** [comment] 2021-09-14 16:22
New doc looks  good (Thanks ! )  but when someone will backup login protector there is a chance of forgetting password so warn about that :) because these are things that you should be aware of, so as not to catch you with your pants down, and without your data :) and docs about such critical software should do that.


Warning message in prompt should include some sort of warning about data loss because if user will only think this is about remembering his password and hence recovery it will be not good. User without any knowledge about .fscrypt dirs won't understand what it means "Protector is on a different filesystem." so my propostition is to add something like that:

`Protector is on a different filesystem. DATA LOSS guaranteed if that filesystem is cleared/destroyed and there is no other recovery set up !!! (Read the docs about recovery for more info and txt file where pass will be generated) Generate a recovery passphrase for new encrypted dir ?`

I think that anyone reading this warning will say yes which is good and harmless.


I also think that metadata commands that where in "Following functionality is planned"  section which is removed now should be the right way to backup/restore/cleanup/recover not the way it is now described in recovery section (I thought that they are implemented already but I was wrong ) but more info about implementation the better.

**Comment by Redsandro** [comment] 2021-09-14 17:35
Weighing in with an opinion:

I suggest we make the recovery password **mandatory**, unless a certain flag (e.g. `--no-create-recovery`) is added to the command for scripting purposes.

Example terminal output:

> **DATA LOSS WARNING**
> Login protector is on a different filesystem. If you lose access to that filesystem, you will automatically lose access to this filesystem. We have created a recovery protector to prevent data loss. **It is vital to write the recovery password down before moving on.** The password is stored in `/foo/bar/recovery.txt`. Now is a good time to write this in your recovery password manager.
> You have been warned.

**Comment by ebiggers** [comment] 2021-09-14 17:58
I made the recovery passphrase mandatory originally, but immediately someone said that they didn't want it and asked how to disable it; see https://github.com/google/fscrypt/issues/186#issuecomment-579011048.  That is why I changed it to a prompt.

Maybe it would be best to be a bit more opinionated though and not have the prompt, but rather just a command-line flag to disable it.  Especially if the explanation of why it was created was clearer.

**Comment by robszy** [comment] 2021-09-14 18:23
If flag is to be the case there should be clearly stated in warning after this command that password should be stored in save place in case of damage of root partition because otherwise DATA LOSS expected

**Comment by Redsandro** [comment] 2021-09-14 20:04
@ebiggers commented:
> Maybe it would be best to be a bit more opinionated though and not have the prompt, but rather just a command-line flag to disable it.

I would recommend this. Better to err on the side of caution, and the command-line flag - that people explicitly need to enter to disable the recovery protector - will satisfy the more daring use case.

Optionally use escape codes for dramatic red colored text when warning the user.

If after that a user still mentions their dissatisfaction with the unwanted recovery passphrase after not having read the documentation, we can mention `fscrypt metadata remove-protector-from-policy`.

**Comment by ebiggers** [comment] 2021-09-16 21:36
@josephlr, @Redsandro, @robszy: I'd appreciate your feedback on https://github.com/google/fscrypt/pull/315, which makes the recovery passphrase generation happen without a prompt again (but with a command-line flag to opt out), and updates the text that is shown.  Thanks!

**Comment by Redsandro** [comment] 2021-09-16 23:58
Thanks for the good work @ebiggers I especially like the pre-filled example command because it's always such a hassle to look up the correct identifiers. :+1:
