### ISSUE TITLE
pam.IsUserLoginToken return no error for locked user

### ISSUE THREAD

**Issue by duminghui1985** [google/fscrypt#133] opened 2019-07-22 19:46 UTC
Hello,

I use pam.IsUserLoginToken()a to login user.
I expect that this function returns error if the user account is locked. But the function returns nil.

The locked (expired) user in shadow file looked like this:
user1:$6$C9K8bVEJ$2OH7o0IqROTvoZpOkb9b9IcXXAWN0viC66B.5npa0sWKeV.Cxq.bKFUOd5mtfUn9bpUUxguSFX6v2J92s4itw/:18098:0:99999:7::1:

The user login through ssh is rejected correctly.

Thanks

**Comment by josephlr** [comment] 2019-07-26 09:00
Thanks for the report @duminghui1985, could you try running the latest master with a debug print [where we call `pam_authenticate`](https://github.com/google/fscrypt/blob/3e32282af2f62829c711593a670e5d893df45196/pam/pam.go#L201)? Knowing the exact status code and error would make this easier to debug.

If [`pam_authenticate`](https://linux.die.net/man/3/pam_authenticate) returns `PAM_SUCCESS`, then there might be an issue with the PAM configuration (either on your side or `fscrypt`'s side, PAM is quite complex). 

For SSH, is your SSH server setup to have `UsePAM yes`? If not, try setting that and seeing what happens.

Also does this issue occur when running as root? The PAM stack is sensitive to that sort of thing.

**Comment by duminghui1985** [comment] 2019-07-31 09:35
Hello @josephlr ,

Thank you for your reply.

pam_authenticate returns PAM_SUCCESS.

SSH server is setup to have UsePAM.

I run the program in the snap on UbuntuCore. So it runs as root.
I also tried to run program out of snap. Running as root is needed. Otherwise the Pam_authenticate always returns PAM_AUTH_ERR, even the user is available.

**Comment by ebiggers** [comment] 2019-11-28 04:57
I tested this (I think) and it works correctly for me, so I'm not sure what we else can do here.

Keep in mind that fscrypt will only check your login passphrase using PAM when it creates a login protector.  If it's adding another directory to an existing login protector, it will only need to check the *protector's* passphrase --- it won't try to authenticate with PAM again.

In other words, if you've run `passwd -l` to prevent a user from logging in, it's expected that `fscrypt` won't allow their login protector to be created.  However, if they already have a login protector, it can still be used.  I think that's working as intended, given that `passwd -l` doesn't truly change the passphrase, but rather temporarily disables logging in (`passwd -u` can re-enable it).

Can you provide more details?  What user-visible `fscrypt` behavior doesn't work for you, exactly?

**Comment by ebiggers** [comment] 2020-03-28 02:07
It's still not clear that anything is actually broken here, and the original reporter hasn't provided more details.  So I'm closing this.

**Closed by ebiggers** 2020-03-28 02:07 UTC
Labels: needs reporter feedback
