### ISSUE TITLE
Authtok is missing

### ISSUE THREAD

**Issue by OdaiGH** [google/fscrypt#324] opened 2021-11-03 15:37 UTC
Dear fscrypt team,

im trying to automatically unlock home dirs (using pam-fscrypt) through ssh connection.
ssh connection is established and is ok. however, the problem is that fscrypt returns `AUTHTOK is missing` when trying to unlock home dirs

two things to be considered :
ChallengeResponseAuthentication is enabled in our ssh (it works fine when we disable it) 
pam is modified to accommodate our system

is there anything should be done to skip authtok or resend the password fscrypt again ?

**Comment by ebiggers** [comment] 2021-12-20 02:49
I believe this is a duplicate of #321, and that the issue is that sshd's `ChallengeResponseAuthentication` (also called `KbdInteractiveAuthentication`) has a [bug](https://bugzilla.mindrot.org/show_bug.cgi?id=2548) which makes it incompatible with `pam_fscrypt`'s auto-unlocking support.  I don't know how to make `pam_fscrypt` work around this in a secure way, so for now I'm just going to document that `PasswordAuthentication` should be used instead of `ChallengeResponseAuthentication`.

**Closed by ebiggers** 2021-12-20 02:49 UTC
