### ISSUE TITLE
[bug] fscrypt encrypt: permission denied: system error: could not link user keyring into root keyring

### ISSUE THREAD

**Issue by outusuke** [google/fscrypt#176] opened 2019-12-15 21:04 UTC
i have this error when running make on zorin os 15.1

go build --ldflags '-s -w -X "main.version=v0.2.5-31-g6821d90" -X "main.buildTime=dom dez 15 18:00:53 -03 2019" -extldflags ""' -o bin/fscrypt ./cmd/fscrypt
metadata/config.go:33:2: cannot find package "github.com/golang/protobuf/jsonpb" in any of:
	/usr/lib/go-1.10/src/github.com/golang/protobuf/jsonpb (from $GOROOT)
	/home/anonimo/go/src/github.com/golang/protobuf/jsonpb (from $GOPATH)
actions/policy.go:26:2: cannot find package "github.com/golang/protobuf/proto" in any of:
	/usr/lib/go-1.10/src/github.com/golang/protobuf/proto (from $GOROOT)
	/home/anonimo/go/src/github.com/golang/protobuf/proto (from $GOPATH)
util/errors.go:28:2: cannot find package "github.com/pkg/errors" in any of:
	/usr/lib/go-1.10/src/github.com/pkg/errors (from $GOROOT)
	/home/anonimo/go/src/github.com/pkg/errors (from $GOPATH)
cmd/fscrypt/commands.go:29:2: cannot find package "github.com/urfave/cli" in any of:
	/usr/lib/go-1.10/src/github.com/urfave/cli (from $GOROOT)
	/home/anonimo/go/src/github.com/urfave/cli (from $GOPATH)
crypto/crypto.go:43:2: cannot find package "golang.org/x/crypto/argon2" in any of:
	/usr/lib/go-1.10/src/golang.org/x/crypto/argon2 (from $GOROOT)
	/home/anonimo/go/src/golang.org/x/crypto/argon2 (from $GOPATH)
crypto/crypto.go:44:2: cannot find package "golang.org/x/crypto/hkdf" in any of:
	/usr/lib/go-1.10/src/golang.org/x/crypto/hkdf (from $GOROOT)
	/home/anonimo/go/src/golang.org/x/crypto/hkdf (from $GOPATH)
cmd/fscrypt/format.go:32:2: cannot find package "golang.org/x/crypto/ssh/terminal" in any of:
	/usr/lib/go-1.10/src/golang.org/x/crypto/ssh/terminal (from $GOROOT)
	/home/anonimo/go/src/golang.org/x/crypto/ssh/terminal (from $GOPATH)
metadata/constants.go:25:2: cannot find package "golang.org/x/sys/unix" in any of:
	/usr/lib/go-1.10/src/golang.org/x/sys/unix (from $GOROOT)
	/home/anonimo/go/src/golang.org/x/sys/unix (from $GOPATH)
Makefile:91: recipe for target 'bin/fscrypt' failed
make: *** [bin/fscrypt] Error 1

_Originally posted by @outusuke in https://github.com/google/fscrypt/issues/109#issuecomment-565846593_

**Comment by ebiggers** [comment] 2019-12-15 21:34
`fscrypt` doesn't support Go 1.10 anymore.  Can you try the latest version of Go?  See: https://github.com/golang/go/wiki/Ubuntu

**Comment by outusuke** [comment] 2019-12-15 22:23
I didn't see that the requirements had changed now it's working,thanks

**Comment by outusuke** [comment] 2019-12-15 23:54
I'm trying to encrypt a user folder and I get this error

fscrypt encrypt: permission denied: system error: could not link user keyring into root keyring

**Comment by outusuke** [comment] 2019-12-16 00:08
solved because of a simple / wasn't going
fscrypt encrypt / home / myuser /

**Comment by outusuke** [comment] 2019-12-16 00:15
I thought it was solved but I was wrong

**Comment by josephlr** [comment] 2019-12-16 01:18
@outusuke can I get the output of the following commands:

```
fscrypt --version
fscrypt status
fscrypt status MOUNTPOINT
fscrypt encrypt DIRECTORY --verbose
fscrypt status DIRECTORY
```

**Comment by ebiggers** [comment] 2019-12-16 03:07
I think I figured out what's going on with the "permission denied" and have opened https://github.com/google/fscrypt/pull/177 to fix it.  Can you test with that commit applied?

However, I think this bug is only possible if your user's keyring isn't linked into the session keyring (assuming you were logged in as the user at the time), which might cause other problems for you too.  If that's the case for you, it's probably caused by https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1754270.  We could try to hack around that in `fscrypt`, but it really needs to be fixed in Ubuntu's `systemd` package.

**Closed** 2019-12-16 03:10 UTC
Labels: bug

**Comment by ebiggers** [comment] 2019-12-17 19:10
@outusuke, my fix for the "permission denied" error was merged to the master branch --- have you had a chance to verify it solved this problem for you?

Also, if your user keyring is not linked into your session keyring (i.e., if running `fscrypt encrypt` complains about it when run as a non-root user, or if `keyctl show` shows a session keyring only), please post some more details on https://github.com/google/fscrypt/issues/100 where that problem has been discussed previously.

Thanks!
