### ISSUE TITLE
Incompatible with xrdp?

### ISSUE THREAD

**Issue by johnsutton** [google/fscrypt#323] opened 2021-10-21 20:07 UTC
I am trying to set up RDP service on my Ubuntu 20.04 system using packages xrdp and xorgxrdp but it simply will not fly!
I'm beginning to suspect that the problem is that my home directory is encrypted using fscrypt...
Does anybody have a view on that possibility?
Thanks.

**Comment by iskunk** [comment] 2022-04-08 06:48
Hi, I have been working on xrdp and fscrypt independently (on Ubuntu even), and figured I'd take a look at this.

It would help if you could check your system logs, and report if you are seeing the same behavior as described in #350.

**Comment by josephlr** [comment] 2022-04-08 10:57
@johnsutton if you're also experiencing hangs, let us know and we can close this bug, and track stuff in #350

**Comment by johnsutton** [comment] 2022-04-08 17:00
@josephlr I'd like to help with this but I'm away from home and my ubuntu system for a couple of weeks.  I'll be back home w/b Mon 25th and will look at it then.

**Comment by ebiggers** [comment] 2023-09-09 17:40
Closing as duplicate of https://github.com/google/fscrypt/issues/350 which has more information

**Closed by ebiggers** 2023-09-09 17:40 UTC
Labels: duplicate
