### ISSUE TITLE
Please provide manpages for fscrypt and pam_fscrypt

### ISSUE THREAD

**Issue by paride** [google/fscrypt#174] opened 2019-11-30 12:25 UTC
Although the README.md is quite complete, not all user are familiar with looking at the documentation it this way. It would be nice to provide proper manpages for the `fscrypt` command and for the `pam_fscrypt` library.

**Comment by ebiggers** [comment] 2019-11-30 19:12
Duplicate of #10

**Closed by ebiggers** 2019-11-30 19:12 UTC
Labels: documentation, duplicate
