### ISSUE TITLE
Problem with sudo?

### ISSUE THREAD

**Issue by HerroBert** [google/fscrypt#290] opened 2021-05-15 12:24 UTC
Hello!

Sometimes I have a problem with a verycrypt file on a fscrypted folder.
Veracrypt uses sudo and root has a problem to access the file: required key is not available

My Kernel is 5.11 with fscrypt 0.2.9 (Ubuntu 21.04)

**Comment by ebiggers** [comment] 2021-05-15 18:16
What is the output of `fscrypt status $dir` where $dir is your encrypted directory?

**Comment by HerroBert** [comment] 2021-05-16 09:05
$ fscrypt status /home/xxxxx/
"/home/xxxxx/" is encrypted with fscrypt.

Policy:   02d9f34f730d7446
Options:  padding:32 contents:AES_256_XTS filenames:AES_256_CTS policy_version:1 
Unlocked: Yes

Protected with 1 protector:
PROTECTOR         LINKED   DESCRIPTION
02e1a799b94412ff  Yes (/)  login protector for xxxxx

**Comment by ebiggers** [comment] 2021-05-16 18:43
This is known/expected behavior for directories that are using a v1 encryption policy, which yours is (due to the directory having been created with kernel v5.3 or earlier and/or `fscrypt` v0.2.6 or earlier).  In order to fix this you'll need to replace the directory with one using a v2 encryption policy, as described at https://github.com/google/fscrypt#cant-log-in-with-ssh-even-when-users-encrypted-home-directory-is-unlocked.

**Comment by HerroBert** [comment] 2021-05-17 16:09
This directory is not locked for root always. Right now it's working.

**Comment by ebiggers** [comment] 2021-05-17 16:37
Yes, that is a known issue with directories that are using a v1 encryption policy.  This was all fixed by v2, so please upgrade your directory.

**Closed** 2021-05-24 21:59 UTC
Labels: question
