### ISSUE TITLE
Unlocking with public key authentication

### ISSUE THREAD

**Issue by giovannikraushaar** [google/fscrypt#180] opened 2020-01-17 21:23 UTC
Auto unlocking when connecting via SSH with public key authentication does not work even if i run `su $(whoami) -c exit` as suggested on the Troubleshooting section of the README.

Will public key be supported in future versions of PAM?

**Comment by ebiggers** [comment] 2020-01-23 02:42
I think this a duplicate of https://github.com/google/fscrypt/issues/116.

**Closed by ebiggers** 2020-01-23 02:42 UTC
Labels: bug, duplicate
