### ISSUE TITLE
fscrypt reports wrong size of symbolic links

### ISSUE THREAD

**Issue by skysley** [google/fscrypt#305] opened 2021-06-30 10:13 UTC
According to the manual of `stat()` the field `stat.st_size` should return the length of the pointed-to pathname:
```
st_size       
        This field gives the size of the file (if it is a regular file or a symbolic link) in bytes.  The size of a symbolic link is the length of the pathname it  contains,  without  a  terminating
        null byte.
```
It seems that fscrypt does not comply with this. Example: A link which points to path "12345" has length 34 on my system.

I stumbled upon this problem when I was trying to find out why I could not generate rpm packages inside an fscrypt-encrypted directory. See [here](https://github.com/rpm-software-management/rpm/issues/1682).

fscrypt --verions: fscrypt version v0.3.0
uname -r: 5.12.13-arch1-2
OS: Arch Linux

**Comment by josephlr** [comment] 2021-06-30 10:26
@ebiggers is this a kernel bug?

**Comment by ebiggers** [comment] 2021-06-30 19:23
This is a known limitation; it's documented at https://www.kernel.org/doc/html/latest/filesystems/fscrypt.html#with-the-key.  The problem is that the symlink would have to be decrypted to get the original size, which would require reading and decrypting a data block, but `stat()` is meant to a be a very lightweight operation that doesn't access data.

Historically this hasn't been feasible at all.  It might be more feasible now that the kernel caches decrypted symlink targets (this happens in Linux v5.2 and later), i.e. now once a symlink target gets decrypted, it stays decrypted.  So now in most cases taking the performance hit on `stat()` would just save the same performance hit later.  So I will consider changing this, but it will have to be weighed against causing a performance regression on stat-only workloads, and the risk of people depending on the current behavior.

It's worth noting that using `st_size` is always racy on a non-readonly filesystem, as the file could have changed after `st_size` was read.  So I'd generally advise against using it for anything other than a hint of how large a buffer to allocate (for which the current behavior works fine, as the reported length is slightly larger than the original length).

**Comment by ebiggers** [comment] 2021-07-02 07:13
I found some other reports of this bug, and I've sent out kernel patches to fix it: https://lkml.kernel.org/linux-fscrypt/20210702065350.209646-1-ebiggers@kernel.org/T/#u

Please note that since this is a longstanding kernel bug/limitation, it won't be possible to get the patches out to all systems and devices that it affects.  If the patches go in (they're targeting kernel version 5.14 or 5.15), I plan to do some backports, but it will be impossible to get them everywhere.  So where this is breaking a userspace tool, a workaround is probably still needed, such as considering the length of the symlink returned by `readlink()` to override the size that `lstat()` reported earlier.  Actually, it's probably a good idea to do that anyway, since unless the tool is only dealing with read-only filesystems, there could always be a race condition where the symlink was deleted and replaced with a different one.

**Comment by ebiggers** [comment] 2021-08-23 17:58
I'm planning to include the above-mentioned kernel patches in my pull request for kernel v5.15.

**Comment by ebiggers** [comment] 2021-08-31 23:54
This bug has been fixed in the mainline Linux kernel, which will be Linux v5.15.  I will update the `fscrypt` documentation to mention this bug and try to ensure that the fix gets backported to at least some of the more recent LTS (Long Term Support) kernel versions.

**Comment by josephlr** [comment] 2021-09-01 02:14
@ebiggers do we want to keep this open to track backports?

**Comment by ebiggers** [comment] 2021-09-01 03:27
Yes, I'll update the documentation again and close this bug once the backports are done.

**Closed** 2021-09-22 19:24 UTC
Labels: bug, documentation
